version: '3.8'
services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: aura-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: aura_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
